### ISSUE TITLE
Rollapp panics after restart if no validators set

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension-rdk#119]
Initial run of a rollapp without validators is working correctly.

When trying to restart the rollapp, a panic received:
```
panic: SetIndex requires index to not be set

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/capability/keeper.Keeper.InitializeIndex({{_, _}, {_, _}, {_, _}, _, _, _}, {{0x1053bc608, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/x/capability/keeper/keeper.go:155 +0x15c
github.com/cosmos/cosmos-sdk/x/capability.InitGenesis({{0x1053bc608, 0x1400013e008}, {0x1053cf998, 0x1400440f440}, {{0x0, 0x0}, {0x14001567330, 0xd}, 0x0, {0x1b708170, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/x/capability/genesis.go:12 +0x94
github.com/cosmos/cosmos-sdk/x/capability.AppModule.InitGenesis({{{_, _}}, {{_, _}, {_, _}, {_, _}, _, _, ...}}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/x/capability/module.go:130 +0xfc
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x1053bc608, 0x1400013e008}, {0x1053cf998, 0x1400440f440}, {{0x0, 0x0}, {0x14001567330, 0xd}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.12/types/module/module.go:327 +0x1ec
github.com/dymensionxyz/rollapp/app.(*App).InitChainer(_, {{0x1053bc608, 0x1400013e008}, {0x1053cf998, 0x1400440f440}, {{0x0, 0x0}, {0x14001567330, 0xd}, 0x0, ...}, ...}, ...)
	github.com/dymensionxyz/rollapp/app/app_evm.go:651 +0x1bc
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0x1400069a1c0, {{0x1b708170, 0xedb92aa33, 0x0}, {0x14001567330, 0xd}, 0x1400205e9a0, {0x106d59750, 0x0, 0x0}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.12/baseapp/abci.go:63 +0x300
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0x140015286c0, {{0x1b708170, 0xedb92aa33, 0x0}, {0x14001567330, 0xd}, 0x1400205e9a0, {0x106d59750, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:272 +0x194
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x14000553bf0?, {{0x1b708170, 0xedb92aa33, 0x0}, {0x14001567330, 0xd}, 0x1400205e9a0, {0x106d59750, 0x0, 0x0}, ...})
	github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:77 +0x84
github.com/dymensionxyz/dymint/state.(*BlockExecutor).InitChain(0x14000816200, 0x1400052c780)
	github.com/dymensionxyz/dymint@v0.3.1-beta.0.20230226100941-6151a3c9d4da/state/executor.go:63 +0x298
github.com/dymensionxyz/dymint/block.NewManager({0x1053c0660?, 0x14001e74918}, {0xbebc200, 0x6fc23ac00, 0x6fc23ac00, 0x0, {0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/dymensionxyz/dymint@v0.3.1-beta.0.20230226100941-6151a3c9d4da/block/manager.go:129 +0x1d4
github.com/dymensionxyz/dymint/node.NewNode({_, _}, {{0x16d98b096, 0x1c}, {0x14002190ea0, 0x4}, {{0x1400158a360, 0x16}, {0x0, 0x0}}, ...}, ...)
	github.com/dymensionxyz/dymint@v0.3.1-beta.0.20230226100941-6151a3c9d4da/node/node.go:149 +0xda0
main.startInProcess(_, {{0x0, 0x0, 0x0}, {0x1053dac98, 0x140021b42d0}, {0x14002190d30, 0xd}, {0x1053c35c8, 0x1400127e530}, ...}, ...)
	github.com/dymensionxyz/rollapp/cmd/evm/start.go:324 +0x680
main.StartCmd.func2(0x14000ffac00?, {0x1400069aa80?, 0x0?, 0x1c?})
	github.com/dymensionxyz/rollapp/cmd/evm/start.go:178 +0x2b8
github.com/spf13/cobra.(*Command).execute(0x14000ffac00, {0x1400069a8c0, 0x1c, 0x1c})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5f4
github.com/spf13/cobra.(*Command).ExecuteC(0x1400110d200)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x14000088768?, {0x140005a21e0, 0x1c})
	github.com/cosmos/cosmos-sdk@v0.45.12/server/cmd/execute.go:36 +0x1a0
main.main()
	github.com/dymensionxyz/rollapp/cmd/evm/main.go:14 +0x40
```

**Comment by mtsitrin** [comment]
To reproduce:
`bash scripts/init_rollapp.sh`

When asked
`Do you want to include staker on genesis? (Y/n)` Press `n`

Then run the rollapp 
`DA_LAYER=mock SETTLEMENT_LAYER=mock LOG_FILE_PATH="/tmp/rollapp.log" bash scripts/run_rollapp.sh`

Then close it, and run it again
